Fix irreverible migration
Trying to revert this migration results in this error:

```
== 20170127173128 FixLimitInSchema: reverting =================================
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

ActiveRecord::IrreversibleMigration/home/tim/src/miq_bot/vendor/bundle/ruby/2.3.0/gems/activerecord-4.2.7/lib/active_record/migration/comman
d_recorder.rb:65:in `inverse_of'
```

We need to tell it explicitly how to undo the change by setting
`:limit => nil`.