[Linter::Base] Fix invalid .linter_env
The argument for `env` passed to `Open3.capture3` (or `Open3.capture2e`)
needs to be a Hash, and not an Array, other wise the following error is
provided:

  ArgumentError: wrong first argument
  /usr/share/ruby/open3.rb:213:in `spawn'
  /usr/share/ruby/open3.rb:213:in `popen_run'
  /usr/share/ruby/open3.rb:101:in `popen3'
  /usr/share/ruby/open3.rb:281:in `capture3'
  /usr/share/gems/gems/awesome_spawn-1.5.0/lib/awesome_spawn.rb:127:in `launch'
  /usr/share/gems/gems/awesome_spawn-1.5.0/lib/awesome_spawn.rb:80:in `run'
  /opt/miq_bot/lib/linter/base.rb:92:in `run_linter'
  /opt/miq_bot/lib/linter/base.rb:27:in `block in run'
  /usr/share/ruby/tmpdir.rb:93:in `mktmpdir'
  /opt/miq_bot/lib/linter/base.rb:18:in `run'
  /opt/miq_bot/app/workers/concerns/code_analysis_mixin.rb:24:in `run_all_linters'
  /opt/miq_bot/app/workers/concerns/code_analysis_mixin.rb:12:in `merged_linter_results'
  /opt/miq_bot/app/workers/commit_monitor_handlers/commit_range/rubocop_checker.rb:25:in `process_branch'
  /opt/miq_bot/app/workers/commit_monitor_handlers/commit_range/rubocop_checker.rb:19:in `perform'