Fix CreateBatchTables migration
Use 4.2 for all of the migrations, since they were all done prior to the
upgrade from 4.2 -> 5.2 and '4.2' is the lowest possible value
available:

    ArgumentError:  Unknown migration version "4.0"; expected one of "4.2", "5.0", "5.1", "5.2"

'4.2' is the closest option that makes sense.