Repo#branches= requires an array.
Fixes a bug from #141

```
/opt/rubies/ruby-2.2.3/lib/ruby/gems/2.2.0/gems/activemodel-4.2.4/lib/active_model/attribute_methods.rb:433:in `method_missing': undefined method `each' for #<Branch:0x00000005bf1ad0> (NoMethodError)
...
  from /opt/miq_bot/app/models/repo.rb:20:in `create_and_clone!'
```